### ISSUE TITLE
Issue with CSS reset -webkit-padding-start: 40px in Chrome

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/polypropylene#1]
``` css
/* Issue with Bootstrap v4.0.0 */
* {
  margin: 0;
  padding: 0;
}
```
